import type { Prisma } from '@prisma/client';

// A single, clearly-named constant rather than a configurable pricing
// system -- there's no existing delivery-fee rule anywhere in this project
// to build on, and the task only calls for cash-on-delivery v1. Easy to
// swap for a real config/settings value later if the business needs it.
export const DELIVERY_FEE_AED = 15;

// Order numbers look like DBG-20260815-0001: a date-scoped, human-typeable
// identifier customers can read over the phone, distinct from the opaque
// cuid `id` used internally. Generated by counting today's orders inside
// the same transaction that creates the order, with a few retries in case
// two checkouts race for the same sequence number.
export function formatOrderDatePart(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  return `${y}${m}${d}`;
}

export async function generateOrderNumber(
  tx: Prisma.TransactionClient,
  attempt = 0,
): Promise<string> {
  const now = new Date();
  const startOfDay = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const startOfNextDay = new Date(startOfDay.getTime() + 24 * 60 * 60 * 1000);

  const countToday = await tx.order.count({
    where: { createdAt: { gte: startOfDay, lt: startOfNextDay } },
  });

  const seq = String(countToday + 1 + attempt).padStart(4, '0');
  const candidate = `DBG-${formatOrderDatePart(now)}-${seq}`;

  const existing = await tx.order.findUnique({ where: { orderNumber: candidate }, select: { id: true } });
  if (existing) {
    if (attempt >= 20) throw new Error('Unable to generate a unique order number.');
    return generateOrderNumber(tx, attempt + 1);
  }

  return candidate;
}

function toNumber(value: { toString(): string }): number {
  return Number(value.toString());
}

export function serializeOrder<
  T extends {
    subtotal: { toString(): string };
    deliveryFee: { toString(): string };
    total: { toString(): string };
    createdAt: Date;
    updatedAt: Date;
  },
>(order: T) {
  return {
    ...order,
    subtotal: toNumber(order.subtotal),
    deliveryFee: toNumber(order.deliveryFee),
    total: toNumber(order.total),
    createdAt: order.createdAt.toISOString(),
    updatedAt: order.updatedAt.toISOString(),
  };
}

export function serializeOrderItem<
  T extends {
    productPriceSnapshot: { toString(): string };
    lineTotal: { toString(): string };
  },
>(item: T) {
  return {
    ...item,
    productPriceSnapshot: toNumber(item.productPriceSnapshot),
    lineTotal: toNumber(item.lineTotal),
  };
}
